# Generated by Django 5.1.4 on 2025-01-30 20:32

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_complaint_official_alter_resident_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='household',
        ),
        migrations.AddField(
            model_name='complaint',
            name='resident',
            field=models.ForeignKey(default=app.models.get_default_resident, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='app.resident'),
        ),
    ]
